services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-node-nodejsimege
    ports:
      - 3000:3000
    volumes:
      - /container/local:/workspaces
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_DB: todos

  mysql:
    image: mysql:latest
    volumes:
      - /container/database:/workspaces/todos/
    environment: 
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data: